/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'brent.gardner' at '11/21/16 2:50 AM' with Gradle 3.1
 *
 * @author brent.gardner, @date 11/21/16 2:50 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
